### ISSUE TITLE
compose-sh: AttributeError: 'Namespace' object has no attribute 'strict'

### ISSUE THREAD

**Issue by vogt4nick** [Dynatrace/alyeska#40]
## Describe the bug

`compose-sh` command line utility throws AttributeError: 'Namespace' object has no attribute 'strict'

## To Reproduce

Using any valid compose configuration, `test.yaml`,

```sh
$ compose-sh test.yaml
Traceback (most recent call last):
  File "/opt/conda/bin/compose-sh", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/alyeska/compose/compose_sh.py", line 211, in main
    output = convert_yaml_to_sh(FLAGS.config_file, FLAGS.strict, FLAGS.ofile)
AttributeError: 'Namespace' object has no attribute 'strict'
```

## Expected behavior

`compose-sh` should execute successfully. 

## Desktop (please complete the following information)

- OS: Ubuntu 16.04

**Comment by vogt4nick** [comment]
Resolved by #41
